config_json:
  - ./Config/other.json
  - ./Config/spaceship.json

config_interaction:
  - ./Interaction/up_deplacement.so
  - ./Interaction/down_deplacement.so
  - ./Interaction/left_deplacement.so
  - ./Interaction/right_deplacement.so

config_component_system:
  - ./ComponentSystem/print.so
# get_yaml("config_json") -> std::vector<std::string>