name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get GCC-10
      run:   |
             sudo apt update
             sudo apt install gcc-10 g++-10
      shell: bash

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends doxygen graphviz  

    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Conan
      run: |
        pip install conan

    - name: Configure Conan
      run: |
        conan user
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan remote add conan-center https://conan.bintray.com

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build with CMake
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release && cmake --build . --config Release