name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends doxygen graphviz  

    - name: Remove grub-efi-amd64-signed error
      run: |
        sudo apt-get install -y grub-efi
        update-grub

    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev pkg-config libxkbfile-dev uuid-dev libxcb-util-dev

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1

    - name: Install Conan
      run: |
        pip install conan

    - name: Configure Conan
      run: |
        conan user
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan remote add conan-center https://conan.bintray.com

    - name: Set up Conan profile
      run: |
        export CONAN_USER_HOME=$HOME/.conan
        export CONAN_USERNAME=<username>
        export CONAN_CHANNEL=<channel>
        export CONAN_REFERENCE=<reference>
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Install dependencies
      run: conan install .

    - name: Install CMake
      run: |
        sudo apt-get update -y
        sudo apt-get install -y software-properties-common lsb-release
        sudo apt-get clean all
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
        sudo apt-get update -y
        sudo apt-get install -y kitware-archive-keyring
        sudo rm /etc/apt/trusted.gpg.d/kitware.gpg
        sudo apt-get update -y
        sudo apt-get install -y cmake

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build with CMake
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release && cmake --build . --config Release